master:
    resource: "@MasterBundle/Controller/"
    type:     annotation
    prefix:   /

chefe:
    resource: "@ChefeBundle/Controller/"
    type:     annotation
    prefix:   /

financeiro:
    resource: "@FinanceiroBundle/Controller/"
    type:     annotation
    prefix:   /financeiro

funcionario:
    resource: "@FuncionarioBundle/Controller/"
    type:     annotation
    prefix:   /funcionario

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: "/logout"