# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        LoginBundle\Entity\Funcionario:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
            
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        auth_provider:
            entity:
                class: LoginBundle:Funcionario
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_secured_area:
            pattern:   ^/
            anonymous: ~
            provider: auth_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /redirectlogin
            logout:
                path:   /logout
                target: login
           
                
    access_control:
             - { path: ^/admin, roles: ROLE_ADMIN }
             - { path: ^/financeiro, roles: ROLE_FINANCEIRO }
             - { path: ^/funcionario, roles: ROLE_FUNCIONARIO }
             - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }